// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { RootGetData, RootGetResponses, HealthCheckHealthCheckGetData, HealthCheckHealthCheckGetResponses, EnsureChatContextChatContextsEnsurePostData, EnsureChatContextChatContextsEnsurePostResponses, EnsureChatContextChatContextsEnsurePostErrors, UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchData, UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchResponses, UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchErrors, ListEvaluationsEvaluationsGetData, ListEvaluationsEvaluationsGetResponses, ListEvaluationsEvaluationsGetErrors, ListChatTemplatesChatTemplatesGetData, ListChatTemplatesChatTemplatesGetResponses, ListChatTemplatesChatTemplatesGetErrors, GetChatTemplateChatTemplatesChatTemplateIdGetData, GetChatTemplateChatTemplatesChatTemplateIdGetResponses, GetChatTemplateChatTemplatesChatTemplateIdGetErrors, ListChatTemplateContainersChatTemplateContainersGetData, ListChatTemplateContainersChatTemplateContainersGetResponses, ListChatTemplateContainersChatTemplateContainersGetErrors, CreateChatCompletionLlmChatCompletionsPostData, CreateChatCompletionLlmChatCompletionsPostResponses, CreateChatCompletionLlmChatCompletionsPostErrors, ListAvailableModelsLlmModelsGetData, ListAvailableModelsLlmModelsGetResponses, ListAvailableModelsLlmModelsGetErrors, CheckLlmHealthLlmHealthGetData, CheckLlmHealthLlmHealthGetResponses, CheckLlmHealthLlmHealthGetErrors, ListBadgesBadgesGetData, ListBadgesBadgesGetResponses, ListBadgesBadgesGetErrors, GetBadgeBadgesBadgeIdGetData, GetBadgeBadgesBadgeIdGetResponses, GetBadgeBadgesBadgeIdGetErrors, GetCurrentUserInfoUsersMeGetData, GetCurrentUserInfoUsersMeGetResponses, GetCurrentUserInfoUsersMeGetErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 * Root endpoint - API information.
 *
 * Provides basic information about the API including version,
 * documentation links, and available endpoints.
 *
 * Returns:
 * dict: API information containing:
 * - message: API description
 * - version: Current API version
 * - docs: Link to interactive API documentation
 * - health_check: Health check endpoint path
 *
 * Example:
 * ```python
 * GET /
 * Response:
 * {
 * "message": "TrustBuilder Wargames AI Backend API",
 * "version": "1.0.0",
 * "docs": "/docs",
 * "health_check": "/health_check"
 * }
 * ```
 *
 * Note:
 * This endpoint is publicly accessible without authentication,
 * making it useful for API discovery and initial integration testing.
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<RootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Health Check
 * Health check endpoint for monitoring and load balancers.
 *
 * Simple endpoint that returns a success status to indicate the
 * service is running and responsive. Used by:
 * - Kubernetes liveness and readiness probes
 * - Load balancer health checks
 * - Monitoring systems (Datadog, New Relic, etc.)
 * - Docker health checks
 *
 * Returns:
 * dict: Health status with "ok" status
 *
 * Example:
 * ```python
 * GET /health_check
 * Response:
 * {
 * "status": "ok"
 * }
 * ```
 *
 * Note:
 * This endpoint is intentionally simple and doesn't check
 * dependencies (database, external services) to ensure it
 * remains fast and reliable. For comprehensive health checks
 * including dependencies, use the /llm/health endpoint for
 * LLM services or implement a separate /health/detailed endpoint.
 */
export const healthCheckHealthCheckGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthCheckGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthCheckHealthCheckGetResponses, unknown, ThrowOnError>({
        url: '/health_check',
        ...options
    });
};

/**
 * Ensure Chat Context
 * Ensure a chat context exists for the current user and template.
 *
 * If the user has no chat context for the template, create one.
 * If one already exists, return it.
 * If more than one exists, return the chat context with the highest id.
 *
 * Args:
 * request: Request containing chat_template_id
 * current_user: Current authenticated user
 * db: Database session
 *
 * Returns:
 * EnsureChatContextResponse with the chat context
 *
 * Raises:
 * HTTPException: 404 if template not found
 */
export const ensureChatContextChatContextsEnsurePost = <ThrowOnError extends boolean = false>(options: Options<EnsureChatContextChatContextsEnsurePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<EnsureChatContextChatContextsEnsurePostResponses, EnsureChatContextChatContextsEnsurePostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/chat_contexts/ensure',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update Chat Context Message Tree
 * Update the message tree of a chat context.
 *
 * If the database row exists and has can_contribute set to true,
 * update the message tree with the user provided message_tree.
 *
 * Args:
 * chat_context_id: ID of the chat context to update
 * request: Request containing the new message tree
 * current_user: Current authenticated user
 * db: Database session
 *
 * Returns:
 * UpdateMessageTreeResponse with the updated chat context
 *
 * Raises:
 * HTTPException: 404 if context not found, 403 if can_contribute is False
 */
export const updateChatContextMessageTreeChatContextsChatContextIdMessageTreePatch = <ThrowOnError extends boolean = false>(options: Options<UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchResponses, UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/chat_contexts/{chat_context_id}/message_tree',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List Evaluations
 * List evaluation results for chat contexts.
 *
 * Returns a list of ChatContextResponse objects for the given chat_template_id,
 * if they exist. If no filter is provided, returns all evaluations.
 *
 * Args:
 * chat_template_id: Optional filter by chat template ID
 * page_index: Page number for pagination (0-indexed)
 * count: Number of items per page
 * current_user: Current authenticated user
 * db: Database session
 *
 * Returns:
 * List of ChatContextResponse objects with evaluation results
 */
export const listEvaluationsEvaluationsGet = <ThrowOnError extends boolean = false>(options?: Options<ListEvaluationsEvaluationsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListEvaluationsEvaluationsGetResponses, ListEvaluationsEvaluationsGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/evaluations',
        ...options
    });
};

/**
 * List Chat Templates
 * List chat templates with filtering options.
 *
 * This is identical to the existing list_chat_templates endpoint.
 *
 * Args:
 * chat_template_container_id: Optional filter by container ID
 * container_type: Optional filter by container type
 * page_index: Page number for pagination (0-indexed)
 * count: Number of items per page
 * db: Database session
 *
 * Returns:
 * List of ChatTemplatesPublic objects with template and container information
 */
export const listChatTemplatesChatTemplatesGet = <ThrowOnError extends boolean = false>(options?: Options<ListChatTemplatesChatTemplatesGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListChatTemplatesChatTemplatesGetResponses, ListChatTemplatesChatTemplatesGetErrors, ThrowOnError>({
        url: '/chat_templates',
        ...options
    });
};

/**
 * Get Chat Template
 * Get detailed information about a specific chat template.
 *
 * Retrieves complete information about a chat template including its
 * name, description, requirements, and associated container.
 * This endpoint does not require authentication.
 *
 * Args:
 * chat_template_id: The unique identifier of the template to retrieve
 * db: Database session
 *
 * Returns:
 * ChatTemplatesPublic: Complete template information including:
 * - chat_template: Full ChatTemplate object with all fields
 * - container_name: Name of the parent container
 *
 * Raises:
 * HTTPException: 404 if template with the specified ID is not found
 *
 * Example:
 * GET /chat_templates/1
 * Response:
 * {
 * "chat_template": {
 * "id": 1,
 * "name": "Introduction Challenge",
 * "description": "Learn the basics",
 * "chat_template_container_id": 5,
 * "required_tools": "["calculator", "search"]",
 * "evaluation_prompt": "User must complete intro",
 * "message_tree": [...]
 * },
 * "container_name": "Tutorial Container"
 * }
 */
export const getChatTemplateChatTemplatesChatTemplateIdGet = <ThrowOnError extends boolean = false>(options: Options<GetChatTemplateChatTemplatesChatTemplateIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetChatTemplateChatTemplatesChatTemplateIdGetResponses, GetChatTemplateChatTemplatesChatTemplateIdGetErrors, ThrowOnError>({
        url: '/chat_templates/{chat_template_id}',
        ...options
    });
};

/**
 * List Chat Template Containers
 * List chat template containers with filtering by date and container type.
 *
 * Retrieves a paginated list of chat template containers based on date filters
 * and optional container type. This endpoint does not require authentication.
 *
 * Args:
 * selection_filter: Filter containers by date. Options include:
 * - ACTIVE_ONLY: Currently active containers (default)
 * - PAST_ONLY: Ended containers
 * - FUTURE_ONLY: Not yet started containers
 * - PAST_AND_ACTIVE: Past and current containers
 * - ACTIVE_AND_FUTURE: Current and upcoming containers
 * container_type: Optional filter by container type (e.g., 'challenge', 'tutorial')
 * page_index: Page number for pagination (0-indexed)
 * count: Number of items per page
 * db: Database session
 *
 * Returns:
 * List of ChatTemplateContainer objects matching the criteria
 *
 * Example:
 * GET /chat_template_containers?selection_filter=ACTIVE_ONLY&container_type=challenge&page_index=0&count=10
 * Response:
 * [
 * {
 * "id": 1,
 * "name": "Beginner Challenges",
 * "type": "challenge",
 * "start_date": "2024-01-01T00:00:00Z",
 * "end_date": "2024-12-31T23:59:59Z",
 * "description": "A collection of beginner-level challenges"
 * }
 * ]
 */
export const listChatTemplateContainersChatTemplateContainersGet = <ThrowOnError extends boolean = false>(options?: Options<ListChatTemplateContainersChatTemplateContainersGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListChatTemplateContainersChatTemplateContainersGetResponses, ListChatTemplateContainersChatTemplateContainersGetErrors, ThrowOnError>({
        url: '/chat_template_containers',
        ...options
    });
};

/**
 * Create Chat Completion
 * Create a chat completion using direct LiteLLM integration.
 *
 * This endpoint uses the LiteLLM library to make direct calls to various
 * LLM providers (OpenAI, Anthropic, GitHub, etc.) without requiring a
 * separate proxy server.
 *
 * Supports both regular (complete) responses and streaming responses using
 * Server-Sent Events (SSE) when stream=true.
 *
 * Args:
 * request: ChatRequest object containing:
 * - model: The model to use (e.g., "gpt-4", "claude-3")
 * - messages: List of chat messages
 * - temperature: Optional sampling temperature
 * - max_tokens: Optional maximum tokens to generate
 * - stream: Whether to stream the response (SSE format)
 * - user: Optional user identifier for tracking
 * current_user: Current authenticated user from JWT token
 *
 * Returns:
 * - If stream=false: ChatResponse with complete response
 * - If stream=true: StreamingResponse with SSE-formatted chunks
 * Each chunk is sent as: "data: {json_chunk}
 *
 * "
 * Final message: "data: [DONE]
 *
 * "
 *
 * Raises:
 * HTTPException: 500 if chat completion fails
 *
 * Example:
 * ```python
 * POST /llm/chat/completions
 * {
 * "model": "gpt-4",
 * "messages": [
 * {"role": "user", "content": "Hello, how are you?"}
 * ],
 * "temperature": 0.7
 * }
 * ```
 */
export const createChatCompletionLlmChatCompletionsPost = <ThrowOnError extends boolean = false>(options: Options<CreateChatCompletionLlmChatCompletionsPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateChatCompletionLlmChatCompletionsPostResponses, CreateChatCompletionLlmChatCompletionsPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/llm/chat/completions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List Available Models
 * List available LLM models.
 *
 * Returns a list of all configured LLM models that have their API keys
 * set and are ready to use. Models without API keys are excluded.
 *
 * Args:
 * current_user: Current authenticated user from JWT token
 *
 * Returns:
 * ModelsResponse: Object containing:
 * - object: Response type (always "list")
 * - data: List of available models with their metadata
 *
 * Raises:
 * HTTPException: 500 if listing models fails
 *
 * Example:
 * ```python
 * GET /llm/models
 * Response:
 * {
 * "object": "list",
 * "data": [
 * {
 * "id": "gpt-4",
 * "object": "model",
 * "created": 1686935002,
 * "owned_by": "openai"
 * },
 * {
 * "id": "claude-3-opus-20240229",
 * "object": "model",
 * "created": 1709251200,
 * "owned_by": "anthropic"
 * }
 * ]
 * }
 * ```
 */
export const listAvailableModelsLlmModelsGet = <ThrowOnError extends boolean = false>(options?: Options<ListAvailableModelsLlmModelsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListAvailableModelsLlmModelsGetResponses, ListAvailableModelsLlmModelsGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/llm/models',
        ...options
    });
};

/**
 * Check Llm Health
 * Check the health status of the LLM service.
 *
 * Provides comprehensive health information about the LLM service including:
 * - Overall service status
 * - List of available models
 * - Configured providers and their status
 * - Missing API keys that need configuration
 *
 * This endpoint is useful for monitoring and debugging LLM integrations.
 *
 * Args:
 * current_user: Current authenticated user from JWT token
 *
 * Returns:
 * LLMHealthStatus: Health status object containing:
 * - healthy: Overall health status boolean
 * - available_models: List of ready-to-use models
 * - providers: Dictionary of provider statuses
 * - missing_keys: List of providers missing API keys
 * - error: Optional error message if unhealthy
 *
 * Raises:
 * HTTPException: 500 if health check fails
 *
 * Example:
 * ```python
 * GET /llm/health
 * Response:
 * {
 * "healthy": true,
 * "available_models": ["gpt-4", "claude-3-opus"],
 * "providers": {
 * "openai": true,
 * "anthropic": true,
 * "github": false
 * },
 * "missing_keys": ["GITHUB_API_KEY"],
 * "error": null
 * }
 * ```
 */
export const checkLlmHealthLlmHealthGet = <ThrowOnError extends boolean = false>(options?: Options<CheckLlmHealthLlmHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<CheckLlmHealthLlmHealthGetResponses, CheckLlmHealthLlmHealthGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/llm/health',
        ...options
    });
};

/**
 * List Badges
 * List badges with optional filtering for user's badges only.
 *
 * This endpoint returns a paginated list of badges. When `user_badges_only`
 * is set to true, it returns only the badges that the current user has earned.
 *
 * Args:
 * user_badges_only: If true, filter to only badges earned by the current user
 * page_index: Page number for pagination (0-indexed)
 * count: Number of items per page (default: 10, max: 100)
 * current_user: Current authenticated user from JWT token
 * db: Database session
 *
 * Returns:
 * List of Badges objects, optionally filtered by user ownership
 *
 * Example:
 * ```python
 * # Get all available badges
 * GET /badges?page_index=0&count=10
 *
 * # Get only the current user's earned badges
 * GET /badges?user_badges_only=true&page_index=0&count=10
 * ```
 */
export const listBadgesBadgesGet = <ThrowOnError extends boolean = false>(options?: Options<ListBadgesBadgesGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListBadgesBadgesGetResponses, ListBadgesBadgesGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/badges',
        ...options
    });
};

/**
 * Get Badge
 * Get detailed information about a specific badge.
 *
 * Retrieves complete information about a badge including its name,
 * description, requirements, and associated chat template.
 *
 * Args:
 * badge_id: The unique identifier of the badge to retrieve
 * current_user: Current authenticated user from JWT token
 * db: Database session
 *
 * Returns:
 * Badges: Complete badge information including:
 * - id: Unique badge identifier
 * - name: Badge name
 * - description: Badge description
 * - icon: Badge icon URL or identifier
 * - chat_template_id: Associated chat template ID
 * - evaluation_prompt: Criteria for earning the badge
 *
 * Raises:
 * HTTPException: 404 if badge with the specified ID is not found
 *
 * Example:
 * ```python
 * GET /badges/1
 * Response:
 * {
 * "id": 1,
 * "name": "First Steps",
 * "description": "Complete your first chat template",
 * "icon": "trophy-gold",
 * "chat_template_id": 5,
 * "evaluation_prompt": "User must complete the introduction template"
 * }
 * ```
 */
export const getBadgeBadgesBadgeIdGet = <ThrowOnError extends boolean = false>(options: Options<GetBadgeBadgesBadgeIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetBadgeBadgesBadgeIdGetResponses, GetBadgeBadgesBadgeIdGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/badges/{badge_id}',
        ...options
    });
};

/**
 * Get Current User Info
 * Get current user information.
 *
 * Retrieves comprehensive information about the currently authenticated user,
 * including their profile details, badges earned, and challenge progress.
 *
 * Args:
 * current_user: Current authenticated user from JWT token
 * db: Database session
 *
 * Returns:
 * UserInfo: Complete user information including:
 * - user: Basic user details (id, username, email, created_at)
 * - badges: List of badges earned by the user
 * - badge_count: Total number of badges earned
 * - contexts: List of active chat template contexts
 * - context_count: Total number of contexts created
 *
 * Example:
 * ```python
 * GET /users/me
 * Response:
 * {
 * "user": {
 * "id": 1,
 * "sub_id": "uuid-from-supabase",
 * "username": "john_doe",
 * "email": "john@example.com",
 * "created_at": "2024-01-15T10:00:00Z"
 * },
 * "badges": [
 * {
 * "id": 1,
 * "name": "First Steps",
 * "description": "Completed first challenge",
 * "earned_at": "2024-01-16T14:30:00Z"
 * }
 * ],
 * "badge_count": 1,
 * "contexts": [
 * {
 * "id": 5,
 * "chat_template_id": 10,
 * "started_at": "2024-01-16T14:00:00Z",
 * "can_contribute": true
 * }
 * ],
 * "context_count": 3
 * }
 * ```
 *
 * Note:
 * This endpoint uses the Supabase user ID (sub_id) to fetch the internal
 * user record and all associated data. The user is automatically created
 * in the internal database if they don't exist yet.
 */
export const getCurrentUserInfoUsersMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserInfoUsersMeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCurrentUserInfoUsersMeGetResponses, GetCurrentUserInfoUsersMeGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options
    });
};