// This file is auto-generated by @hey-api/openapi-ts

/**
 * Badges
 */
export type Badges = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Chat Template Id
     */
    chat_template_id: number;
};

/**
 * ChatChoice
 * A single choice in the chat completion response.
 *
 * Attributes:
 * index: The index of this choice.
 * message: The message generated by the model.
 * finish_reason: The reason the model stopped generating.
 */
export type ChatChoice = {
    /**
     * Index
     */
    index: number;
    message: ChatMessage;
    /**
     * Finish Reason
     */
    finish_reason: string | null;
};

/**
 * ChatContext
 */
export type ChatContext = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Can Contribute
     */
    can_contribute: boolean;
    /**
     * Chat Template Id
     */
    chat_template_id: number;
    /**
     * Started At
     */
    started_at: string;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Message Tree
     */
    message_tree?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ChatContextResponse
 * Represents the full message context for a chat template, including user chat template context
 * and messages.
 */
export type ChatContextResponse = {
    user_chat_template_context: ChatContext;
    eval_result?: EvalResult | null;
    /**
     * Remaining Message Count
     */
    remaining_message_count?: number;
};

/**
 * ChatMessage
 * A single chat message in the conversation.
 *
 * Attributes:
 * role: The role of the message sender (user, assistant, system).
 * content: The content of the message.
 * name: Optional name of the message sender.
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     */
    content: string;
    /**
     * Name
     */
    name?: string | null;
};

/**
 * ChatRequest
 * Request model for chat completions.
 *
 * Attributes:
 * model: The model to use for completion.
 * messages: List of messages in the conversation.
 * temperature: Sampling temperature (0.0 to 2.0).
 * max_tokens: Maximum tokens in the response.
 * stream: Whether to stream the response.
 * user: Optional user identifier for tracking.
 */
export type ChatRequest = {
    /**
     * Model
     */
    model: string;
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * Temperature
     */
    temperature?: number | null;
    /**
     * Max Tokens
     */
    max_tokens?: number | null;
    /**
     * Stream
     */
    stream?: boolean | null;
    /**
     * User
     */
    user?: string | null;
};

/**
 * ChatResponse
 * Response model for chat completions.
 *
 * Attributes:
 * id: Unique identifier for the completion.
 * object: The object type (always "chat.completion").
 * created: Unix timestamp of when the completion was created.
 * model: The model used for the completion.
 * choices: List of completion choices.
 * usage: Token usage information.
 */
export type ChatResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Object
     */
    object: string;
    /**
     * Created
     */
    created: number;
    /**
     * Model
     */
    model: string;
    /**
     * Choices
     */
    choices: Array<ChatChoice>;
    usage?: ChatUsage | null;
};

/**
 * ChatTemplate
 */
export type ChatTemplate = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Chat Template Container Id
     */
    chat_template_container_id: number;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Required Tools
     */
    required_tools?: string | null;
    /**
     * Evaluation Prompt
     */
    evaluation_prompt?: string | null;
    /**
     * Message Tree
     */
    message_tree?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ChatTemplateContainer
 */
export type ChatTemplateContainer = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
};

/**
 * ChatTemplatesPublic
 */
export type ChatTemplatesPublic = {
    chat_template: ChatTemplate;
    /**
     * Container Name
     */
    container_name: string;
};

/**
 * ChatUsage
 * Token usage information for the chat completion.
 *
 * Attributes:
 * prompt_tokens: Number of tokens in the prompt.
 * completion_tokens: Number of tokens in the completion.
 * total_tokens: Total number of tokens used.
 */
export type ChatUsage = {
    /**
     * Prompt Tokens
     */
    prompt_tokens: number;
    /**
     * Completion Tokens
     */
    completion_tokens: number;
    /**
     * Total Tokens
     */
    total_tokens: number;
};

/**
 * EnsureChatContextRequest
 * Request body for ensuring chat context exists.
 */
export type EnsureChatContextRequest = {
    /**
     * Chat Template Id
     */
    chat_template_id: number;
};

/**
 * EnsureChatContextResponse
 * Response for ensure chat context endpoint.
 */
export type EnsureChatContextResponse = {
    chat_context: ChatContext;
};

/**
 * EvalResult
 */
export type EvalResult = {
    /**
     * Reason
     */
    reason?: string | null;
    status: EvalStatus;
    /**
     * Chat Template Id
     */
    chat_template_id?: number | null;
};

/**
 * EvalStatus
 */
export type EvalStatus = 'NOT_EVALUATED' | 'SUCCEEDED' | 'FAILED' | 'ERRORED';

/**
 * FunctionCall
 * Function call details within a tool call.
 *
 * Attributes:
 * name: The name of the function to call.
 * arguments: The arguments to call the function with (as JSON string).
 */
export type FunctionCall = {
    /**
     * Name
     */
    name: string;
    /**
     * Arguments
     */
    arguments: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LLMHealthStatus
 * Health status response for LLM service.
 *
 * Attributes:
 * status: Health status (healthy, unhealthy, degraded).
 * available_models: Number of models with valid API keys.
 * missing_keys: List of missing API key environment variables.
 * message: Human-readable status message.
 * details: Additional status details.
 */
export type LlmHealthStatus = {
    /**
     * Status
     */
    status: 'healthy' | 'unhealthy' | 'degraded';
    /**
     * Available Models
     */
    available_models: number;
    /**
     * Missing Keys
     */
    missing_keys: Array<string>;
    /**
     * Message
     */
    message: string;
    /**
     * Details
     */
    details?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Message
 */
export type Message = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Is Tool Call
     */
    is_tool_call?: boolean;
    /**
     * Tool Name
     */
    tool_name?: string | null;
    /**
     * Tool Calls
     */
    tool_calls?: Array<ToolCall> | null;
    /**
     * Tool Call Id
     */
    tool_call_id?: string | null;
    /**
     * Model
     */
    model?: string | null;
};

/**
 * MessageContainer
 * Container for a message with its position in the message tree.
 *
 * Used for the ScrollyTell feature to represent hierarchical message structures.
 *
 * Attributes:
 * id_in_tree: Tree-scoped identifier for the message container (not database ID).
 * parent_id_in_tree: Tree-scoped ID of the parent message, null for root.
 * message: The actual message content.
 */
export type MessageContainer = {
    /**
     * Id In Tree
     * Tree-scoped identifier for the message container
     */
    id_in_tree: number;
    /**
     * Parent Id In Tree
     * Tree-scoped ID of the parent message, null for root
     */
    parent_id_in_tree?: number | null;
    /**
     * The actual message content
     */
    message: Message;
};

/**
 * ModelInfo
 * Information about an available model.
 *
 * Attributes:
 * id: The model identifier.
 * object: The object type (always "model").
 * created: Unix timestamp of when the model was created.
 * owned_by: The organization that owns the model.
 * display_name: Human-readable name for UI display.
 * description: Model description.
 * max_tokens: Maximum tokens supported.
 */
export type ModelInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Object
     */
    object?: string;
    /**
     * Created
     */
    created: number;
    /**
     * Owned By
     */
    owned_by: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Max Tokens
     */
    max_tokens?: number | null;
};

/**
 * ModelsResponse
 * Response model for listing available models.
 *
 * Attributes:
 * object: The object type (always "list").
 * data: List of available models.
 */
export type ModelsResponse = {
    /**
     * Object
     */
    object?: string;
    /**
     * Data
     */
    data: Array<ModelInfo>;
};

/**
 * SelectionFilter
 */
export type SelectionFilter = 'PAST' | 'ACTIVE' | 'FUTURE' | 'PAST_AND_ACTIVE' | 'ACTIVE_AND_FUTURE';

/**
 * ToolCall
 * A tool call request from the model.
 *
 * Attributes:
 * id: Unique identifier for this tool call.
 * type: The type of tool call (currently only 'function').
 * function: The function call details.
 */
export type ToolCall = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type?: 'function';
    function: FunctionCall;
};

/**
 * UpdateMessageTreeRequest
 * Request body for updating message tree.
 */
export type UpdateMessageTreeRequest = {
    /**
     * Message Tree
     */
    message_tree: Array<MessageContainer>;
};

/**
 * UpdateMessageTreeResponse
 * Response for update message tree endpoint.
 */
export type UpdateMessageTreeResponse = {
    chat_context: ChatContext;
};

/**
 * UserInfo
 * Represents a user's information including active chat template containers, chat templates,
 * and badges.
 */
export type UserInfo = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Active Chat Template Containers
     */
    active_chat_template_containers: Array<ChatTemplateContainer>;
    /**
     * Active Chat Template Contexts
     */
    active_chat_template_contexts: Array<ChatContext>;
    /**
     * Badges
     */
    badges: Array<Badges>;
    /**
     * Eval Results
     */
    eval_results?: Array<EvalResult>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthCheckGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health_check';
};

export type HealthCheckHealthCheckGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EnsureChatContextChatContextsEnsurePostData = {
    body: EnsureChatContextRequest;
    path?: never;
    query?: never;
    url: '/chat_contexts/ensure';
};

export type EnsureChatContextChatContextsEnsurePostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnsureChatContextChatContextsEnsurePostError = EnsureChatContextChatContextsEnsurePostErrors[keyof EnsureChatContextChatContextsEnsurePostErrors];

export type EnsureChatContextChatContextsEnsurePostResponses = {
    /**
     * Successful Response
     */
    200: EnsureChatContextResponse;
};

export type EnsureChatContextChatContextsEnsurePostResponse = EnsureChatContextChatContextsEnsurePostResponses[keyof EnsureChatContextChatContextsEnsurePostResponses];

export type UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchData = {
    body: UpdateMessageTreeRequest;
    path: {
        /**
         * Chat Context Id
         */
        chat_context_id: number;
    };
    query?: never;
    url: '/chat_contexts/{chat_context_id}/message_tree';
};

export type UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchError = UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchErrors[keyof UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchErrors];

export type UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchResponses = {
    /**
     * Successful Response
     */
    200: UpdateMessageTreeResponse;
};

export type UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchResponse = UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchResponses[keyof UpdateChatContextMessageTreeChatContextsChatContextIdMessageTreePatchResponses];

export type DeleteChatContextChatContextsChatContextIdDeleteData = {
    body?: never;
    path: {
        /**
         * Chat Context Id
         */
        chat_context_id: number;
    };
    query?: never;
    url: '/chat_contexts/{chat_context_id}';
};

export type DeleteChatContextChatContextsChatContextIdDeleteErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChatContextChatContextsChatContextIdDeleteError = DeleteChatContextChatContextsChatContextIdDeleteErrors[keyof DeleteChatContextChatContextsChatContextIdDeleteErrors];

export type DeleteChatContextChatContextsChatContextIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteChatContextChatContextsChatContextIdDeleteResponse = DeleteChatContextChatContextsChatContextIdDeleteResponses[keyof DeleteChatContextChatContextsChatContextIdDeleteResponses];

export type ListEvaluationsEvaluationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Chat Template Id
         */
        chat_template_id?: number | null;
        /**
         * Page Index
         */
        page_index?: number;
        /**
         * Count
         */
        count?: number;
    };
    url: '/evaluations';
};

export type ListEvaluationsEvaluationsGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEvaluationsEvaluationsGetError = ListEvaluationsEvaluationsGetErrors[keyof ListEvaluationsEvaluationsGetErrors];

export type ListEvaluationsEvaluationsGetResponses = {
    /**
     * Response List Evaluations Evaluations Get
     * Successful Response
     */
    200: Array<ChatContextResponse>;
};

export type ListEvaluationsEvaluationsGetResponse = ListEvaluationsEvaluationsGetResponses[keyof ListEvaluationsEvaluationsGetResponses];

export type ListChatTemplatesChatTemplatesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Chat Template Container Id
         */
        chat_template_container_id?: number | null;
        /**
         * Container Type
         */
        container_type?: string | null;
        /**
         * Page Index
         */
        page_index?: number;
        /**
         * Count
         */
        count?: number;
    };
    url: '/chat_templates';
};

export type ListChatTemplatesChatTemplatesGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChatTemplatesChatTemplatesGetError = ListChatTemplatesChatTemplatesGetErrors[keyof ListChatTemplatesChatTemplatesGetErrors];

export type ListChatTemplatesChatTemplatesGetResponses = {
    /**
     * Response List Chat Templates Chat Templates Get
     * Successful Response
     */
    200: Array<ChatTemplatesPublic>;
};

export type ListChatTemplatesChatTemplatesGetResponse = ListChatTemplatesChatTemplatesGetResponses[keyof ListChatTemplatesChatTemplatesGetResponses];

export type GetChatTemplateChatTemplatesChatTemplateIdGetData = {
    body?: never;
    path: {
        /**
         * Chat Template Id
         */
        chat_template_id: number;
    };
    query?: never;
    url: '/chat_templates/{chat_template_id}';
};

export type GetChatTemplateChatTemplatesChatTemplateIdGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatTemplateChatTemplatesChatTemplateIdGetError = GetChatTemplateChatTemplatesChatTemplateIdGetErrors[keyof GetChatTemplateChatTemplatesChatTemplateIdGetErrors];

export type GetChatTemplateChatTemplatesChatTemplateIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChatTemplatesPublic;
};

export type GetChatTemplateChatTemplatesChatTemplateIdGetResponse = GetChatTemplateChatTemplatesChatTemplateIdGetResponses[keyof GetChatTemplateChatTemplatesChatTemplateIdGetResponses];

export type ListChatTemplateContainersChatTemplateContainersGetData = {
    body?: never;
    path?: never;
    query?: {
        selection_filter?: SelectionFilter;
        /**
         * Container Type
         */
        container_type?: string | null;
        /**
         * Page Index
         */
        page_index?: number;
        /**
         * Count
         */
        count?: number;
    };
    url: '/chat_template_containers';
};

export type ListChatTemplateContainersChatTemplateContainersGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChatTemplateContainersChatTemplateContainersGetError = ListChatTemplateContainersChatTemplateContainersGetErrors[keyof ListChatTemplateContainersChatTemplateContainersGetErrors];

export type ListChatTemplateContainersChatTemplateContainersGetResponses = {
    /**
     * Response List Chat Template Containers Chat Template Containers Get
     * Successful Response
     */
    200: Array<ChatTemplateContainer>;
};

export type ListChatTemplateContainersChatTemplateContainersGetResponse = ListChatTemplateContainersChatTemplateContainersGetResponses[keyof ListChatTemplateContainersChatTemplateContainersGetResponses];

export type CreateChatCompletionLlmChatCompletionsPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/llm/chat/completions';
};

export type CreateChatCompletionLlmChatCompletionsPostErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateChatCompletionLlmChatCompletionsPostError = CreateChatCompletionLlmChatCompletionsPostErrors[keyof CreateChatCompletionLlmChatCompletionsPostErrors];

export type CreateChatCompletionLlmChatCompletionsPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type CreateChatCompletionLlmChatCompletionsPostResponse = CreateChatCompletionLlmChatCompletionsPostResponses[keyof CreateChatCompletionLlmChatCompletionsPostResponses];

export type ListAvailableModelsLlmModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/llm/models';
};

export type ListAvailableModelsLlmModelsGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListAvailableModelsLlmModelsGetResponses = {
    /**
     * Successful Response
     */
    200: ModelsResponse;
};

export type ListAvailableModelsLlmModelsGetResponse = ListAvailableModelsLlmModelsGetResponses[keyof ListAvailableModelsLlmModelsGetResponses];

export type CheckLlmHealthLlmHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/llm/health';
};

export type CheckLlmHealthLlmHealthGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CheckLlmHealthLlmHealthGetResponses = {
    /**
     * Successful Response
     */
    200: LlmHealthStatus;
};

export type CheckLlmHealthLlmHealthGetResponse = CheckLlmHealthLlmHealthGetResponses[keyof CheckLlmHealthLlmHealthGetResponses];

export type ListBadgesBadgesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * User Badges Only
         */
        user_badges_only?: boolean;
        /**
         * Page Index
         */
        page_index?: number;
        /**
         * Count
         */
        count?: number;
    };
    url: '/badges';
};

export type ListBadgesBadgesGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBadgesBadgesGetError = ListBadgesBadgesGetErrors[keyof ListBadgesBadgesGetErrors];

export type ListBadgesBadgesGetResponses = {
    /**
     * Response List Badges Badges Get
     * Successful Response
     */
    200: Array<Badges>;
};

export type ListBadgesBadgesGetResponse = ListBadgesBadgesGetResponses[keyof ListBadgesBadgesGetResponses];

export type GetBadgeBadgesBadgeIdGetData = {
    body?: never;
    path: {
        /**
         * Badge Id
         */
        badge_id: number;
    };
    query?: never;
    url: '/badges/{badge_id}';
};

export type GetBadgeBadgesBadgeIdGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBadgeBadgesBadgeIdGetError = GetBadgeBadgesBadgeIdGetErrors[keyof GetBadgeBadgesBadgeIdGetErrors];

export type GetBadgeBadgesBadgeIdGetResponses = {
    /**
     * Successful Response
     */
    200: Badges;
};

export type GetBadgeBadgesBadgeIdGetResponse = GetBadgeBadgesBadgeIdGetResponses[keyof GetBadgeBadgesBadgeIdGetResponses];

export type GetCurrentUserInfoUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserInfoUsersMeGetErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetCurrentUserInfoUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type GetCurrentUserInfoUsersMeGetResponse = GetCurrentUserInfoUsersMeGetResponses[keyof GetCurrentUserInfoUsersMeGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};