// This file is auto-generated by @hey-api/openapi-ts

/**
 * Badges
 */
export type Badges = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Chat Template Id
     */
    chat_template_id: number;
};

/**
 * ChatChoice
 * A single choice in the chat completion response.
 *
 * Attributes:
 * index: The index of this choice.
 * message: The message generated by the model.
 * finish_reason: The reason the model stopped generating.
 */
export type ChatChoice = {
    /**
     * Index
     */
    index: number;
    message: ChatMessage;
    /**
     * Finish Reason
     */
    finish_reason: string | null;
};

/**
 * ChatMessage
 * A single chat message in the conversation.
 *
 * Attributes:
 * role: The role of the message sender (user, assistant, system).
 * content: The content of the message.
 * name: Optional name of the message sender.
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     */
    content: string;
    /**
     * Name
     */
    name?: string | null;
};

/**
 * ChatRequest
 * Request model for chat completions.
 *
 * Attributes:
 * model: The model to use for completion.
 * messages: List of messages in the conversation.
 * temperature: Sampling temperature (0.0 to 2.0).
 * max_tokens: Maximum tokens in the response.
 * stream: Whether to stream the response.
 * user: Optional user identifier for tracking.
 */
export type ChatRequest = {
    /**
     * Model
     */
    model: string;
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * Temperature
     */
    temperature?: number | null;
    /**
     * Max Tokens
     */
    max_tokens?: number | null;
    /**
     * Stream
     */
    stream?: boolean | null;
    /**
     * User
     */
    user?: string | null;
};

/**
 * ChatResponse
 * Response model for chat completions.
 *
 * Attributes:
 * id: Unique identifier for the completion.
 * object: The object type (always "chat.completion").
 * created: Unix timestamp of when the completion was created.
 * model: The model used for the completion.
 * choices: List of completion choices.
 * usage: Token usage information.
 */
export type ChatResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Object
     */
    object: string;
    /**
     * Created
     */
    created: number;
    /**
     * Model
     */
    model: string;
    /**
     * Choices
     */
    choices: Array<ChatChoice>;
    usage?: ChatUsage | null;
};

/**
 * ChatTemplate
 */
export type ChatTemplate = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Chat Template Container Id
     */
    chat_template_container_id: number;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Required Tools
     */
    required_tools?: string | null;
    /**
     * Evaluation Prompt
     */
    evaluation_prompt?: string | null;
    /**
     * Message Tree
     */
    message_tree?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ChatTemplateContainer
 */
export type ChatTemplateContainer = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
};

/**
 * ChatTemplateContextLLMResponse
 * Represents a response from the LLM call.
 */
export type ChatTemplateContextLlmResponse = {
    /**
     * Remaining Message Count
     */
    remaining_message_count: number;
    /**
     * Messages
     */
    messages: Array<Message>;
};

/**
 * ChatTemplateContextResponse
 * Represents the full message context for a chat template, including user chat template context
 * and messages.
 */
export type ChatTemplateContextResponse = {
    user_chat_template_context: UserChatTemplateContext;
    /**
     * Messages
     */
    messages?: Array<Message>;
    eval_result?: EvalResult | null;
    /**
     * Remaining Message Count
     */
    remaining_message_count?: number;
};

/**
 * ChatTemplatesPublic
 */
export type ChatTemplatesPublic = {
    chat_template: ChatTemplate;
    /**
     * Container Name
     */
    container_name: string;
};

/**
 * ChatUsage
 * Token usage information for the chat completion.
 *
 * Attributes:
 * prompt_tokens: Number of tokens in the prompt.
 * completion_tokens: Number of tokens in the completion.
 * total_tokens: Total number of tokens used.
 */
export type ChatUsage = {
    /**
     * Prompt Tokens
     */
    prompt_tokens: number;
    /**
     * Completion Tokens
     */
    completion_tokens: number;
    /**
     * Total Tokens
     */
    total_tokens: number;
};

/**
 * EvalResult
 */
export type EvalResult = {
    /**
     * Reason
     */
    reason?: string | null;
    status: EvalStatus;
    /**
     * Chat Template Id
     */
    chat_template_id?: number | null;
};

/**
 * EvalStatus
 */
export type EvalStatus = 'NOT_EVALUATED' | 'SUCCEEDED' | 'FAILED' | 'ERRORED';

/**
 * FunctionCall
 * Function call details within a tool call.
 *
 * Attributes:
 * name: The name of the function to call.
 * arguments: The arguments to call the function with (as JSON string).
 */
export type FunctionCall = {
    /**
     * Name
     */
    name: string;
    /**
     * Arguments
     */
    arguments: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LLMHealthStatus
 * Health status response for LLM service.
 *
 * Attributes:
 * status: Health status (healthy, unhealthy, degraded).
 * available_models: Number of models with valid API keys.
 * missing_keys: List of missing API key environment variables.
 * message: Human-readable status message.
 * details: Additional status details.
 */
export type LlmHealthStatus = {
    /**
     * Status
     */
    status: 'healthy' | 'unhealthy' | 'degraded';
    /**
     * Available Models
     */
    available_models: number;
    /**
     * Missing Keys
     */
    missing_keys: Array<string>;
    /**
     * Message
     */
    message: string;
    /**
     * Details
     */
    details?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Message
 */
export type Message = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Is Tool Call
     */
    is_tool_call?: boolean;
    /**
     * Tool Name
     */
    tool_name?: string | null;
    /**
     * Tool Calls
     */
    tool_calls?: Array<ToolCall> | null;
    /**
     * Tool Call Id
     */
    tool_call_id?: string | null;
};

/**
 * MessageContainer
 * Container for a message with its position in the message tree.
 *
 * Used for the ScrollyTell feature to represent hierarchical message structures.
 *
 * Attributes:
 * id: Unique identifier for the message container.
 * parent_message_id: ID of the parent message, null for root.
 * message: The actual message content.
 */
export type MessageContainer = {
    /**
     * Id
     * Unique identifier for the message container
     */
    id: number;
    /**
     * Parent Message Id
     * ID of the parent message, null for root
     */
    parent_message_id?: number | null;
    /**
     * The actual message content
     */
    message: Message;
};

/**
 * ModelInfo
 * Information about an available model.
 *
 * Attributes:
 * id: The model identifier.
 * object: The object type (always "model").
 * created: Unix timestamp of when the model was created.
 * owned_by: The organization that owns the model.
 * display_name: Human-readable name for UI display.
 * description: Model description.
 * max_tokens: Maximum tokens supported.
 */
export type ModelInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Object
     */
    object?: string;
    /**
     * Created
     */
    created: number;
    /**
     * Owned By
     */
    owned_by: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Max Tokens
     */
    max_tokens?: number | null;
};

/**
 * ModelsResponse
 * Response model for listing available models.
 *
 * Attributes:
 * object: The object type (always "list").
 * data: List of available models.
 */
export type ModelsResponse = {
    /**
     * Object
     */
    object?: string;
    /**
     * Data
     */
    data: Array<ModelInfo>;
};

/**
 * SelectionFilter
 */
export type SelectionFilter = 'PAST' | 'ACTIVE' | 'FUTURE' | 'PAST_AND_ACTIVE' | 'ACTIVE_AND_FUTURE';

/**
 * ToolCall
 * A tool call request from the model.
 *
 * Attributes:
 * id: Unique identifier for this tool call.
 * type: The type of tool call (currently only 'function').
 * function: The function call details.
 */
export type ToolCall = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type?: 'function';
    function: FunctionCall;
};

/**
 * UserChatTemplateContext
 */
export type UserChatTemplateContext = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Can Contribute
     */
    can_contribute: boolean;
    /**
     * Chat Template Id
     */
    chat_template_id: number;
    /**
     * Started At
     */
    started_at: string;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Last Message Version
     */
    last_message_version: number;
    /**
     * Processing Token
     */
    processing_token?: string | null;
    /**
     * Processing Started At
     */
    processing_started_at?: string | null;
    /**
     * Last Message Id
     */
    last_message_id?: number | null;
};

/**
 * UserInfo
 * Represents a user's information including active chat template containers, chat templates,
 * and badges.
 */
export type UserInfo = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Active Chat Template Containers
     */
    active_chat_template_containers: Array<ChatTemplateContainer>;
    /**
     * Active Chat Template Contexts
     */
    active_chat_template_contexts: Array<UserChatTemplateContext>;
    /**
     * Badges
     */
    badges: Array<Badges>;
    /**
     * Eval Results
     */
    eval_results?: Array<EvalResult>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListChatTemplateContainersChatTemplateContainersGetData = {
    body?: never;
    path?: never;
    query?: {
        selection_filter?: SelectionFilter;
        /**
         * Container Type
         */
        container_type?: string | null;
        /**
         * Page Index
         */
        page_index?: number;
        /**
         * Count
         */
        count?: number;
    };
    url: '/chat_template_containers';
};

export type ListChatTemplateContainersChatTemplateContainersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChatTemplateContainersChatTemplateContainersGetError = ListChatTemplateContainersChatTemplateContainersGetErrors[keyof ListChatTemplateContainersChatTemplateContainersGetErrors];

export type ListChatTemplateContainersChatTemplateContainersGetResponses = {
    /**
     * Response List Chat Template Containers Chat Template Containers Get
     * Successful Response
     */
    200: Array<ChatTemplateContainer>;
};

export type ListChatTemplateContainersChatTemplateContainersGetResponse = ListChatTemplateContainersChatTemplateContainersGetResponses[keyof ListChatTemplateContainersChatTemplateContainersGetResponses];

export type GetChatTemplateContainerChatTemplateContainersChatTemplateContainerIdGetData = {
    body?: never;
    path: {
        /**
         * Chat Template Container Id
         */
        chat_template_container_id: number;
    };
    query?: never;
    url: '/chat_template_containers/{chat_template_container_id}';
};

export type GetChatTemplateContainerChatTemplateContainersChatTemplateContainerIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatTemplateContainerChatTemplateContainersChatTemplateContainerIdGetError = GetChatTemplateContainerChatTemplateContainersChatTemplateContainerIdGetErrors[keyof GetChatTemplateContainerChatTemplateContainersChatTemplateContainerIdGetErrors];

export type GetChatTemplateContainerChatTemplateContainersChatTemplateContainerIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChatTemplateContainer;
};

export type GetChatTemplateContainerChatTemplateContainersChatTemplateContainerIdGetResponse = GetChatTemplateContainerChatTemplateContainersChatTemplateContainerIdGetResponses[keyof GetChatTemplateContainerChatTemplateContainersChatTemplateContainerIdGetResponses];

export type ListBadgesBadgesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * User Badges Only
         */
        user_badges_only?: boolean;
        /**
         * Page Index
         */
        page_index?: number;
        /**
         * Count
         */
        count?: number;
    };
    url: '/badges';
};

export type ListBadgesBadgesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBadgesBadgesGetError = ListBadgesBadgesGetErrors[keyof ListBadgesBadgesGetErrors];

export type ListBadgesBadgesGetResponses = {
    /**
     * Response List Badges Badges Get
     * Successful Response
     */
    200: Array<Badges>;
};

export type ListBadgesBadgesGetResponse = ListBadgesBadgesGetResponses[keyof ListBadgesBadgesGetResponses];

export type GetBadgeBadgesBadgeIdGetData = {
    body?: never;
    path: {
        /**
         * Badge Id
         */
        badge_id: number;
    };
    query?: never;
    url: '/badges/{badge_id}';
};

export type GetBadgeBadgesBadgeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBadgeBadgesBadgeIdGetError = GetBadgeBadgesBadgeIdGetErrors[keyof GetBadgeBadgesBadgeIdGetErrors];

export type GetBadgeBadgesBadgeIdGetResponses = {
    /**
     * Successful Response
     */
    200: Badges;
};

export type GetBadgeBadgesBadgeIdGetResponse = GetBadgeBadgesBadgeIdGetResponses[keyof GetBadgeBadgesBadgeIdGetResponses];

export type ListChatTemplatesChatTemplatesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Chat Template Container Id
         */
        chat_template_container_id?: number | null;
        /**
         * Container Type
         */
        container_type?: string | null;
        /**
         * Page Index
         */
        page_index?: number;
        /**
         * Count
         */
        count?: number;
    };
    url: '/chat_templates';
};

export type ListChatTemplatesChatTemplatesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChatTemplatesChatTemplatesGetError = ListChatTemplatesChatTemplatesGetErrors[keyof ListChatTemplatesChatTemplatesGetErrors];

export type ListChatTemplatesChatTemplatesGetResponses = {
    /**
     * Response List Chat Templates Chat Templates Get
     * Successful Response
     */
    200: Array<ChatTemplatesPublic>;
};

export type ListChatTemplatesChatTemplatesGetResponse = ListChatTemplatesChatTemplatesGetResponses[keyof ListChatTemplatesChatTemplatesGetResponses];

export type StartChatTemplateChatTemplatesChatTemplateIdStartPostData = {
    body?: never;
    path: {
        /**
         * Chat Template Id
         */
        chat_template_id: number;
    };
    query?: never;
    url: '/chat_templates/{chat_template_id}/start';
};

export type StartChatTemplateChatTemplatesChatTemplateIdStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartChatTemplateChatTemplatesChatTemplateIdStartPostError = StartChatTemplateChatTemplatesChatTemplateIdStartPostErrors[keyof StartChatTemplateChatTemplatesChatTemplateIdStartPostErrors];

export type StartChatTemplateChatTemplatesChatTemplateIdStartPostResponses = {
    /**
     * Successful Response
     */
    200: UserChatTemplateContext;
};

export type StartChatTemplateChatTemplatesChatTemplateIdStartPostResponse = StartChatTemplateChatTemplatesChatTemplateIdStartPostResponses[keyof StartChatTemplateChatTemplatesChatTemplateIdStartPostResponses];

export type AddMessageToChatTemplateChatTemplatesChatTemplateIdAddMessagePostData = {
    body?: never;
    path: {
        /**
         * Chat Template Id
         */
        chat_template_id: number;
    };
    query: {
        /**
         * Message
         */
        message: string;
        /**
         * Role
         */
        role?: 'user' | 'assistant' | 'system';
        /**
         * Solicit Llm Response
         */
        solicit_llm_response?: boolean;
    };
    url: '/chat_templates/{chat_template_id}/add_message';
};

export type AddMessageToChatTemplateChatTemplatesChatTemplateIdAddMessagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMessageToChatTemplateChatTemplatesChatTemplateIdAddMessagePostError = AddMessageToChatTemplateChatTemplatesChatTemplateIdAddMessagePostErrors[keyof AddMessageToChatTemplateChatTemplatesChatTemplateIdAddMessagePostErrors];

export type AddMessageToChatTemplateChatTemplatesChatTemplateIdAddMessagePostResponses = {
    /**
     * Successful Response
     */
    200: ChatTemplateContextLlmResponse;
};

export type AddMessageToChatTemplateChatTemplatesChatTemplateIdAddMessagePostResponse = AddMessageToChatTemplateChatTemplatesChatTemplateIdAddMessagePostResponses[keyof AddMessageToChatTemplateChatTemplatesChatTemplateIdAddMessagePostResponses];

export type EvaluateChatTemplateContextChatTemplatesChatTemplateIdEvaluateGetData = {
    body?: never;
    path: {
        /**
         * Chat Template Id
         */
        chat_template_id: number;
    };
    query?: never;
    url: '/chat_templates/{chat_template_id}/evaluate';
};

export type EvaluateChatTemplateContextChatTemplatesChatTemplateIdEvaluateGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EvaluateChatTemplateContextChatTemplatesChatTemplateIdEvaluateGetError = EvaluateChatTemplateContextChatTemplatesChatTemplateIdEvaluateGetErrors[keyof EvaluateChatTemplateContextChatTemplatesChatTemplateIdEvaluateGetErrors];

export type EvaluateChatTemplateContextChatTemplatesChatTemplateIdEvaluateGetResponses = {
    /**
     * Successful Response
     */
    200: EvalResult;
};

export type EvaluateChatTemplateContextChatTemplatesChatTemplateIdEvaluateGetResponse = EvaluateChatTemplateContextChatTemplatesChatTemplateIdEvaluateGetResponses[keyof EvaluateChatTemplateContextChatTemplatesChatTemplateIdEvaluateGetResponses];

export type GetCurrentUserInfoUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserInfoUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type GetCurrentUserInfoUsersMeGetResponse = GetCurrentUserInfoUsersMeGetResponses[keyof GetCurrentUserInfoUsersMeGetResponses];

export type GetChatTemplateContextChatTemplatesChatTemplateIdContextGetData = {
    body?: never;
    path: {
        /**
         * Chat Template Id
         */
        chat_template_id: number;
    };
    query?: never;
    url: '/chat_templates/{chat_template_id}/context';
};

export type GetChatTemplateContextChatTemplatesChatTemplateIdContextGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatTemplateContextChatTemplatesChatTemplateIdContextGetError = GetChatTemplateContextChatTemplatesChatTemplateIdContextGetErrors[keyof GetChatTemplateContextChatTemplatesChatTemplateIdContextGetErrors];

export type GetChatTemplateContextChatTemplatesChatTemplateIdContextGetResponses = {
    /**
     * Successful Response
     */
    200: ChatTemplateContextResponse;
};

export type GetChatTemplateContextChatTemplatesChatTemplateIdContextGetResponse = GetChatTemplateContextChatTemplatesChatTemplateIdContextGetResponses[keyof GetChatTemplateContextChatTemplatesChatTemplateIdContextGetResponses];

export type GetMessageTreeMessageTreeUserChatTemplateContextIdGetData = {
    body?: never;
    path: {
        /**
         * User Chat Template Context Id
         */
        user_chat_template_context_id: number;
    };
    query?: never;
    url: '/message_tree/{user_chat_template_context_id}';
};

export type GetMessageTreeMessageTreeUserChatTemplateContextIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMessageTreeMessageTreeUserChatTemplateContextIdGetError = GetMessageTreeMessageTreeUserChatTemplateContextIdGetErrors[keyof GetMessageTreeMessageTreeUserChatTemplateContextIdGetErrors];

export type GetMessageTreeMessageTreeUserChatTemplateContextIdGetResponses = {
    /**
     * Response Get Message Tree Message Tree  User Chat Template Context Id  Get
     * Successful Response
     */
    200: Array<MessageContainer>;
};

export type GetMessageTreeMessageTreeUserChatTemplateContextIdGetResponse = GetMessageTreeMessageTreeUserChatTemplateContextIdGetResponses[keyof GetMessageTreeMessageTreeUserChatTemplateContextIdGetResponses];

export type CreateChatCompletionLlmChatCompletionsPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/llm/chat/completions';
};

export type CreateChatCompletionLlmChatCompletionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChatCompletionLlmChatCompletionsPostError = CreateChatCompletionLlmChatCompletionsPostErrors[keyof CreateChatCompletionLlmChatCompletionsPostErrors];

export type CreateChatCompletionLlmChatCompletionsPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type CreateChatCompletionLlmChatCompletionsPostResponse = CreateChatCompletionLlmChatCompletionsPostResponses[keyof CreateChatCompletionLlmChatCompletionsPostResponses];

export type ListAvailableModelsLlmModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/llm/models';
};

export type ListAvailableModelsLlmModelsGetResponses = {
    /**
     * Successful Response
     */
    200: ModelsResponse;
};

export type ListAvailableModelsLlmModelsGetResponse = ListAvailableModelsLlmModelsGetResponses[keyof ListAvailableModelsLlmModelsGetResponses];

export type CheckLlmHealthLlmHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/llm/health';
};

export type CheckLlmHealthLlmHealthGetResponses = {
    /**
     * Successful Response
     */
    200: LlmHealthStatus;
};

export type CheckLlmHealthLlmHealthGetResponse = CheckLlmHealthLlmHealthGetResponses[keyof CheckLlmHealthLlmHealthGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthCheckGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health_check';
};

export type HealthCheckHealthCheckGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};